README.md: Fix snapd install instructions
On Xubuntu 16.10, following the README.md instructions gives this message:
 > error: unknown flag `clasic'

However, if the argument order is changed, it works just fine.