ubuntu: window: Fix complile error
Following instructions from the compliler we're swapping out
mir_surface_get_buffer_stream() for mir_window_get_buffer_stream()

anbox/src/anbox/ubuntu/window.cpp:81:28: error:
  ‘MirBufferStream* mir_surface_get_buffer_stream(MirSurface*)’ is deprecated:
   use mir_window_get_buffer_stream() instead [-Werror=deprecated-declarations]

Signed-off-by: Lee Jones <lee.jones@linaro.org>